# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.2

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = "/Users/tigerz/Library/Application Support/stm32cube/bundles/cmake/4.2.3+st.1/CMake.app/Contents/bin/cmake"

# The command to remove a file.
RM = "/Users/tigerz/Library/Application Support/stm32cube/bundles/cmake/4.2.3+st.1/CMake.app/Contents/bin/cmake" -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /Users/tigerz/Documents/School/UMich/eecs_373/project/stm32/pvz-with-hud

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /Users/tigerz/Documents/School/UMich/eecs_373/project/stm32/pvz-with-hud

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	"/Users/tigerz/Library/Application Support/stm32cube/bundles/cmake/4.2.3+st.1/CMake.app/Contents/bin/ccmake" -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	"/Users/tigerz/Library/Application Support/stm32cube/bundles/cmake/4.2.3+st.1/CMake.app/Contents/bin/cmake" --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tigerz/Documents/School/UMich/eecs_373/project/stm32/pvz-with-hud/CMakeFiles /Users/tigerz/Documents/School/UMich/eecs_373/project/stm32/pvz-with-hud//CMakeFiles/progress.marks
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /Users/tigerz/Documents/School/UMich/eecs_373/project/stm32/pvz-with-hud/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named pvz-with-hud

# Build rule for target.
pvz-with-hud: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pvz-with-hud
.PHONY : pvz-with-hud

# fast build rule for target.
pvz-with-hud/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/build
.PHONY : pvz-with-hud/fast

#=============================================================================
# Target rules for targets named pvz

# Build rule for target.
pvz: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 pvz
.PHONY : pvz

# fast build rule for target.
pvz/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/build
.PHONY : pvz/fast

#=============================================================================
# Target rules for targets named tft_display

# Build rule for target.
tft_display: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 tft_display
.PHONY : tft_display

# fast build rule for target.
tft_display/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tft_display.dir/build.make CMakeFiles/tft_display.dir/build
.PHONY : tft_display/fast

#=============================================================================
# Target rules for targets named hub75_display

# Build rule for target.
hub75_display: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 hub75_display
.PHONY : hub75_display

# fast build rule for target.
hub75_display/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hub75_display.dir/build.make CMakeFiles/hub75_display.dir/build
.PHONY : hub75_display/fast

#=============================================================================
# Target rules for targets named STM32_Drivers

# Build rule for target.
STM32_Drivers: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 STM32_Drivers
.PHONY : STM32_Drivers

# fast build rule for target.
STM32_Drivers/fast:
	$(MAKE) $(MAKESILENT) -f cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build.make cmake/stm32cubemx/CMakeFiles/STM32_Drivers.dir/build
.PHONY : STM32_Drivers/fast

Core/Src/main.o: Core/Src/main.c.o
.PHONY : Core/Src/main.o

# target to build an object file
Core/Src/main.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/main.c.o
.PHONY : Core/Src/main.c.o

Core/Src/main.i: Core/Src/main.c.i
.PHONY : Core/Src/main.i

# target to preprocess a source file
Core/Src/main.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/main.c.i
.PHONY : Core/Src/main.c.i

Core/Src/main.s: Core/Src/main.c.s
.PHONY : Core/Src/main.s

# target to generate assembly for a file
Core/Src/main.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/main.c.s
.PHONY : Core/Src/main.c.s

Core/Src/pvz_frontend.o: Core/Src/pvz_frontend.c.o
.PHONY : Core/Src/pvz_frontend.o

# target to build an object file
Core/Src/pvz_frontend.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/pvz_frontend.c.o
.PHONY : Core/Src/pvz_frontend.c.o

Core/Src/pvz_frontend.i: Core/Src/pvz_frontend.c.i
.PHONY : Core/Src/pvz_frontend.i

# target to preprocess a source file
Core/Src/pvz_frontend.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/pvz_frontend.c.i
.PHONY : Core/Src/pvz_frontend.c.i

Core/Src/pvz_frontend.s: Core/Src/pvz_frontend.c.s
.PHONY : Core/Src/pvz_frontend.s

# target to generate assembly for a file
Core/Src/pvz_frontend.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/pvz_frontend.c.s
.PHONY : Core/Src/pvz_frontend.c.s

Core/Src/stm32l4xx_hal_msp.o: Core/Src/stm32l4xx_hal_msp.c.o
.PHONY : Core/Src/stm32l4xx_hal_msp.o

# target to build an object file
Core/Src/stm32l4xx_hal_msp.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/stm32l4xx_hal_msp.c.o
.PHONY : Core/Src/stm32l4xx_hal_msp.c.o

Core/Src/stm32l4xx_hal_msp.i: Core/Src/stm32l4xx_hal_msp.c.i
.PHONY : Core/Src/stm32l4xx_hal_msp.i

# target to preprocess a source file
Core/Src/stm32l4xx_hal_msp.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/stm32l4xx_hal_msp.c.i
.PHONY : Core/Src/stm32l4xx_hal_msp.c.i

Core/Src/stm32l4xx_hal_msp.s: Core/Src/stm32l4xx_hal_msp.c.s
.PHONY : Core/Src/stm32l4xx_hal_msp.s

# target to generate assembly for a file
Core/Src/stm32l4xx_hal_msp.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/stm32l4xx_hal_msp.c.s
.PHONY : Core/Src/stm32l4xx_hal_msp.c.s

Core/Src/stm32l4xx_it.o: Core/Src/stm32l4xx_it.c.o
.PHONY : Core/Src/stm32l4xx_it.o

# target to build an object file
Core/Src/stm32l4xx_it.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/stm32l4xx_it.c.o
.PHONY : Core/Src/stm32l4xx_it.c.o

Core/Src/stm32l4xx_it.i: Core/Src/stm32l4xx_it.c.i
.PHONY : Core/Src/stm32l4xx_it.i

# target to preprocess a source file
Core/Src/stm32l4xx_it.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/stm32l4xx_it.c.i
.PHONY : Core/Src/stm32l4xx_it.c.i

Core/Src/stm32l4xx_it.s: Core/Src/stm32l4xx_it.c.s
.PHONY : Core/Src/stm32l4xx_it.s

# target to generate assembly for a file
Core/Src/stm32l4xx_it.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/stm32l4xx_it.c.s
.PHONY : Core/Src/stm32l4xx_it.c.s

Core/Src/syscalls.o: Core/Src/syscalls.c.o
.PHONY : Core/Src/syscalls.o

# target to build an object file
Core/Src/syscalls.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/syscalls.c.o
.PHONY : Core/Src/syscalls.c.o

Core/Src/syscalls.i: Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.i

# target to preprocess a source file
Core/Src/syscalls.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/syscalls.c.i
.PHONY : Core/Src/syscalls.c.i

Core/Src/syscalls.s: Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.s

# target to generate assembly for a file
Core/Src/syscalls.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/syscalls.c.s
.PHONY : Core/Src/syscalls.c.s

Core/Src/sysmem.o: Core/Src/sysmem.c.o
.PHONY : Core/Src/sysmem.o

# target to build an object file
Core/Src/sysmem.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/sysmem.c.o
.PHONY : Core/Src/sysmem.c.o

Core/Src/sysmem.i: Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.i

# target to preprocess a source file
Core/Src/sysmem.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/sysmem.c.i
.PHONY : Core/Src/sysmem.c.i

Core/Src/sysmem.s: Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.s

# target to generate assembly for a file
Core/Src/sysmem.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/Core/Src/sysmem.c.s
.PHONY : Core/Src/sysmem.c.s

libs/hub75_display/hub75.o: libs/hub75_display/hub75.c.o
.PHONY : libs/hub75_display/hub75.o

# target to build an object file
libs/hub75_display/hub75.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hub75_display.dir/build.make CMakeFiles/hub75_display.dir/libs/hub75_display/hub75.c.o
.PHONY : libs/hub75_display/hub75.c.o

libs/hub75_display/hub75.i: libs/hub75_display/hub75.c.i
.PHONY : libs/hub75_display/hub75.i

# target to preprocess a source file
libs/hub75_display/hub75.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hub75_display.dir/build.make CMakeFiles/hub75_display.dir/libs/hub75_display/hub75.c.i
.PHONY : libs/hub75_display/hub75.c.i

libs/hub75_display/hub75.s: libs/hub75_display/hub75.c.s
.PHONY : libs/hub75_display/hub75.s

# target to generate assembly for a file
libs/hub75_display/hub75.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/hub75_display.dir/build.make CMakeFiles/hub75_display.dir/libs/hub75_display/hub75.c.s
.PHONY : libs/hub75_display/hub75.c.s

libs/pvz/src/app.o: libs/pvz/src/app.c.o
.PHONY : libs/pvz/src/app.o

# target to build an object file
libs/pvz/src/app.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/app.c.o
.PHONY : libs/pvz/src/app.c.o

libs/pvz/src/app.i: libs/pvz/src/app.c.i
.PHONY : libs/pvz/src/app.i

# target to preprocess a source file
libs/pvz/src/app.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/app.c.i
.PHONY : libs/pvz/src/app.c.i

libs/pvz/src/app.s: libs/pvz/src/app.c.s
.PHONY : libs/pvz/src/app.s

# target to generate assembly for a file
libs/pvz/src/app.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/app.c.s
.PHONY : libs/pvz/src/app.c.s

libs/pvz/src/game.o: libs/pvz/src/game.c.o
.PHONY : libs/pvz/src/game.o

# target to build an object file
libs/pvz/src/game.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/game.c.o
.PHONY : libs/pvz/src/game.c.o

libs/pvz/src/game.i: libs/pvz/src/game.c.i
.PHONY : libs/pvz/src/game.i

# target to preprocess a source file
libs/pvz/src/game.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/game.c.i
.PHONY : libs/pvz/src/game.c.i

libs/pvz/src/game.s: libs/pvz/src/game.c.s
.PHONY : libs/pvz/src/game.s

# target to generate assembly for a file
libs/pvz/src/game.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/game.c.s
.PHONY : libs/pvz/src/game.c.s

libs/pvz/src/game_types.o: libs/pvz/src/game_types.c.o
.PHONY : libs/pvz/src/game_types.o

# target to build an object file
libs/pvz/src/game_types.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/game_types.c.o
.PHONY : libs/pvz/src/game_types.c.o

libs/pvz/src/game_types.i: libs/pvz/src/game_types.c.i
.PHONY : libs/pvz/src/game_types.i

# target to preprocess a source file
libs/pvz/src/game_types.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/game_types.c.i
.PHONY : libs/pvz/src/game_types.c.i

libs/pvz/src/game_types.s: libs/pvz/src/game_types.c.s
.PHONY : libs/pvz/src/game_types.s

# target to generate assembly for a file
libs/pvz/src/game_types.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/game_types.c.s
.PHONY : libs/pvz/src/game_types.c.s

libs/pvz/src/input.o: libs/pvz/src/input.c.o
.PHONY : libs/pvz/src/input.o

# target to build an object file
libs/pvz/src/input.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/input.c.o
.PHONY : libs/pvz/src/input.c.o

libs/pvz/src/input.i: libs/pvz/src/input.c.i
.PHONY : libs/pvz/src/input.i

# target to preprocess a source file
libs/pvz/src/input.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/input.c.i
.PHONY : libs/pvz/src/input.c.i

libs/pvz/src/input.s: libs/pvz/src/input.c.s
.PHONY : libs/pvz/src/input.s

# target to generate assembly for a file
libs/pvz/src/input.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/input.c.s
.PHONY : libs/pvz/src/input.c.s

libs/pvz/src/placeholder_scene.o: libs/pvz/src/placeholder_scene.c.o
.PHONY : libs/pvz/src/placeholder_scene.o

# target to build an object file
libs/pvz/src/placeholder_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/placeholder_scene.c.o
.PHONY : libs/pvz/src/placeholder_scene.c.o

libs/pvz/src/placeholder_scene.i: libs/pvz/src/placeholder_scene.c.i
.PHONY : libs/pvz/src/placeholder_scene.i

# target to preprocess a source file
libs/pvz/src/placeholder_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/placeholder_scene.c.i
.PHONY : libs/pvz/src/placeholder_scene.c.i

libs/pvz/src/placeholder_scene.s: libs/pvz/src/placeholder_scene.c.s
.PHONY : libs/pvz/src/placeholder_scene.s

# target to generate assembly for a file
libs/pvz/src/placeholder_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/placeholder_scene.c.s
.PHONY : libs/pvz/src/placeholder_scene.c.s

libs/pvz/src/play_scene.o: libs/pvz/src/play_scene.c.o
.PHONY : libs/pvz/src/play_scene.o

# target to build an object file
libs/pvz/src/play_scene.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/play_scene.c.o
.PHONY : libs/pvz/src/play_scene.c.o

libs/pvz/src/play_scene.i: libs/pvz/src/play_scene.c.i
.PHONY : libs/pvz/src/play_scene.i

# target to preprocess a source file
libs/pvz/src/play_scene.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/play_scene.c.i
.PHONY : libs/pvz/src/play_scene.c.i

libs/pvz/src/play_scene.s: libs/pvz/src/play_scene.c.s
.PHONY : libs/pvz/src/play_scene.s

# target to generate assembly for a file
libs/pvz/src/play_scene.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/play_scene.c.s
.PHONY : libs/pvz/src/play_scene.c.s

libs/pvz/src/presentation.o: libs/pvz/src/presentation.c.o
.PHONY : libs/pvz/src/presentation.o

# target to build an object file
libs/pvz/src/presentation.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/presentation.c.o
.PHONY : libs/pvz/src/presentation.c.o

libs/pvz/src/presentation.i: libs/pvz/src/presentation.c.i
.PHONY : libs/pvz/src/presentation.i

# target to preprocess a source file
libs/pvz/src/presentation.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/presentation.c.i
.PHONY : libs/pvz/src/presentation.c.i

libs/pvz/src/presentation.s: libs/pvz/src/presentation.c.s
.PHONY : libs/pvz/src/presentation.s

# target to generate assembly for a file
libs/pvz/src/presentation.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/presentation.c.s
.PHONY : libs/pvz/src/presentation.c.s

libs/pvz/src/pvz_config.o: libs/pvz/src/pvz_config.c.o
.PHONY : libs/pvz/src/pvz_config.o

# target to build an object file
libs/pvz/src/pvz_config.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/pvz_config.c.o
.PHONY : libs/pvz/src/pvz_config.c.o

libs/pvz/src/pvz_config.i: libs/pvz/src/pvz_config.c.i
.PHONY : libs/pvz/src/pvz_config.i

# target to preprocess a source file
libs/pvz/src/pvz_config.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/pvz_config.c.i
.PHONY : libs/pvz/src/pvz_config.c.i

libs/pvz/src/pvz_config.s: libs/pvz/src/pvz_config.c.s
.PHONY : libs/pvz/src/pvz_config.s

# target to generate assembly for a file
libs/pvz/src/pvz_config.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/pvz_config.c.s
.PHONY : libs/pvz/src/pvz_config.c.s

libs/pvz/src/pvz_rect.o: libs/pvz/src/pvz_rect.c.o
.PHONY : libs/pvz/src/pvz_rect.o

# target to build an object file
libs/pvz/src/pvz_rect.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/pvz_rect.c.o
.PHONY : libs/pvz/src/pvz_rect.c.o

libs/pvz/src/pvz_rect.i: libs/pvz/src/pvz_rect.c.i
.PHONY : libs/pvz/src/pvz_rect.i

# target to preprocess a source file
libs/pvz/src/pvz_rect.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/pvz_rect.c.i
.PHONY : libs/pvz/src/pvz_rect.c.i

libs/pvz/src/pvz_rect.s: libs/pvz/src/pvz_rect.c.s
.PHONY : libs/pvz/src/pvz_rect.s

# target to generate assembly for a file
libs/pvz/src/pvz_rect.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/pvz_rect.c.s
.PHONY : libs/pvz/src/pvz_rect.c.s

libs/pvz/src/pvz_utils.o: libs/pvz/src/pvz_utils.c.o
.PHONY : libs/pvz/src/pvz_utils.o

# target to build an object file
libs/pvz/src/pvz_utils.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/pvz_utils.c.o
.PHONY : libs/pvz/src/pvz_utils.c.o

libs/pvz/src/pvz_utils.i: libs/pvz/src/pvz_utils.c.i
.PHONY : libs/pvz/src/pvz_utils.i

# target to preprocess a source file
libs/pvz/src/pvz_utils.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/pvz_utils.c.i
.PHONY : libs/pvz/src/pvz_utils.c.i

libs/pvz/src/pvz_utils.s: libs/pvz/src/pvz_utils.c.s
.PHONY : libs/pvz/src/pvz_utils.s

# target to generate assembly for a file
libs/pvz/src/pvz_utils.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/pvz_utils.c.s
.PHONY : libs/pvz/src/pvz_utils.c.s

libs/pvz/src/render_assets.o: libs/pvz/src/render_assets.c.o
.PHONY : libs/pvz/src/render_assets.o

# target to build an object file
libs/pvz/src/render_assets.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/render_assets.c.o
.PHONY : libs/pvz/src/render_assets.c.o

libs/pvz/src/render_assets.i: libs/pvz/src/render_assets.c.i
.PHONY : libs/pvz/src/render_assets.i

# target to preprocess a source file
libs/pvz/src/render_assets.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/render_assets.c.i
.PHONY : libs/pvz/src/render_assets.c.i

libs/pvz/src/render_assets.s: libs/pvz/src/render_assets.c.s
.PHONY : libs/pvz/src/render_assets.s

# target to generate assembly for a file
libs/pvz/src/render_assets.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz.dir/build.make CMakeFiles/pvz.dir/libs/pvz/src/render_assets.c.s
.PHONY : libs/pvz/src/render_assets.c.s

libs/tft_display/ili9488.o: libs/tft_display/ili9488.c.o
.PHONY : libs/tft_display/ili9488.o

# target to build an object file
libs/tft_display/ili9488.c.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tft_display.dir/build.make CMakeFiles/tft_display.dir/libs/tft_display/ili9488.c.o
.PHONY : libs/tft_display/ili9488.c.o

libs/tft_display/ili9488.i: libs/tft_display/ili9488.c.i
.PHONY : libs/tft_display/ili9488.i

# target to preprocess a source file
libs/tft_display/ili9488.c.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tft_display.dir/build.make CMakeFiles/tft_display.dir/libs/tft_display/ili9488.c.i
.PHONY : libs/tft_display/ili9488.c.i

libs/tft_display/ili9488.s: libs/tft_display/ili9488.c.s
.PHONY : libs/tft_display/ili9488.s

# target to generate assembly for a file
libs/tft_display/ili9488.c.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/tft_display.dir/build.make CMakeFiles/tft_display.dir/libs/tft_display/ili9488.c.s
.PHONY : libs/tft_display/ili9488.c.s

startup_stm32l4r5xx.o: startup_stm32l4r5xx.s.o
.PHONY : startup_stm32l4r5xx.o

# target to build an object file
startup_stm32l4r5xx.s.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/pvz-with-hud.dir/build.make CMakeFiles/pvz-with-hud.dir/startup_stm32l4r5xx.s.o
.PHONY : startup_stm32l4r5xx.s.o

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... STM32_Drivers"
	@echo "... hub75_display"
	@echo "... pvz"
	@echo "... pvz-with-hud"
	@echo "... tft_display"
	@echo "... Core/Src/main.o"
	@echo "... Core/Src/main.i"
	@echo "... Core/Src/main.s"
	@echo "... Core/Src/pvz_frontend.o"
	@echo "... Core/Src/pvz_frontend.i"
	@echo "... Core/Src/pvz_frontend.s"
	@echo "... Core/Src/stm32l4xx_hal_msp.o"
	@echo "... Core/Src/stm32l4xx_hal_msp.i"
	@echo "... Core/Src/stm32l4xx_hal_msp.s"
	@echo "... Core/Src/stm32l4xx_it.o"
	@echo "... Core/Src/stm32l4xx_it.i"
	@echo "... Core/Src/stm32l4xx_it.s"
	@echo "... Core/Src/syscalls.o"
	@echo "... Core/Src/syscalls.i"
	@echo "... Core/Src/syscalls.s"
	@echo "... Core/Src/sysmem.o"
	@echo "... Core/Src/sysmem.i"
	@echo "... Core/Src/sysmem.s"
	@echo "... libs/hub75_display/hub75.o"
	@echo "... libs/hub75_display/hub75.i"
	@echo "... libs/hub75_display/hub75.s"
	@echo "... libs/pvz/src/app.o"
	@echo "... libs/pvz/src/app.i"
	@echo "... libs/pvz/src/app.s"
	@echo "... libs/pvz/src/game.o"
	@echo "... libs/pvz/src/game.i"
	@echo "... libs/pvz/src/game.s"
	@echo "... libs/pvz/src/game_types.o"
	@echo "... libs/pvz/src/game_types.i"
	@echo "... libs/pvz/src/game_types.s"
	@echo "... libs/pvz/src/input.o"
	@echo "... libs/pvz/src/input.i"
	@echo "... libs/pvz/src/input.s"
	@echo "... libs/pvz/src/placeholder_scene.o"
	@echo "... libs/pvz/src/placeholder_scene.i"
	@echo "... libs/pvz/src/placeholder_scene.s"
	@echo "... libs/pvz/src/play_scene.o"
	@echo "... libs/pvz/src/play_scene.i"
	@echo "... libs/pvz/src/play_scene.s"
	@echo "... libs/pvz/src/presentation.o"
	@echo "... libs/pvz/src/presentation.i"
	@echo "... libs/pvz/src/presentation.s"
	@echo "... libs/pvz/src/pvz_config.o"
	@echo "... libs/pvz/src/pvz_config.i"
	@echo "... libs/pvz/src/pvz_config.s"
	@echo "... libs/pvz/src/pvz_rect.o"
	@echo "... libs/pvz/src/pvz_rect.i"
	@echo "... libs/pvz/src/pvz_rect.s"
	@echo "... libs/pvz/src/pvz_utils.o"
	@echo "... libs/pvz/src/pvz_utils.i"
	@echo "... libs/pvz/src/pvz_utils.s"
	@echo "... libs/pvz/src/render_assets.o"
	@echo "... libs/pvz/src/render_assets.i"
	@echo "... libs/pvz/src/render_assets.s"
	@echo "... libs/tft_display/ili9488.o"
	@echo "... libs/tft_display/ili9488.i"
	@echo "... libs/tft_display/ili9488.s"
	@echo "... startup_stm32l4r5xx.o"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

